### ISSUE TITLE
echo -n end_marker being printed to stdout

### ISSUE THREAD

**Issue by ice-wzl** [JusticeRage/FFM#13]
- I've seen the end marker being printed to stdout during my testing.
- I found `end_marker` in the `input_api.py` file. 
- After forking and starting work I thought it was potentially something I introduced but cloned a fresh untouched copy and the issue persists.
- Opening an issue because I am not sure exactly how to fix this or what is causing it to print to stdout.
- Using `terminator` and `zsh` and `terminator` and `bash` on another host. Tested on both, see below.

## Steps to reproduce 
- Occurs both sshed to a machine w/o a `pty` and in a `pty` on a local `kali` system with `zsh`
- In pty on local system (kali)
````
python3 ffm.py
!os
cat /etc/*release*
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION="2023.1"
VERSION_ID="2023.1"
VERSION_CODENAME="kali-rolling"
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
                                                                                                                                      
┌──(kali㉿kali)-[/opt/justice-ffm/FFM]
echo -n
IJVzPmNFQumMGiuPRRpyZMPFRUVkHHeo            
````
- I did not enter the `echo -n` command
### SSH'ed with no `pty` 
````
!os
cat /etc/*release*
echo -n WNGwrqHpyzOhRwRghOvenIHUzGXWNsVk
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
````
- Happy to assist you trying to fix this issue.  Cheers.

**Comment by JusticeRage** [comment]
Hi! It's been a long time since I've worked on this project, but I vaguely remember this being an issue on occasion.
Basically, something challenging is detecting when a command has finished printing output. When using a PTY, there is usually a prompt (i.e., `root@kali #>`) which can be used as a delimiter. FFM tries to detect such a string with a [regular expression](https://github.com/JusticeRage/FFM/blob/ad691d4e978a573a660c3ce0fa7b0249e07b8d17/ffm.py#L43) that mostly worked back then, but not so much now that prompts have those weird characters ("┌──") in them.

When FFM cannot detect the presence of a prompt, it falls back to an [alternate solution](https://github.com/JusticeRage/FFM/blob/ad691d4e978a573a660c3ce0fa7b0249e07b8d17/model/driver/input_api.py#L83), which is printing a random string before and after the command. This string then acts as a delimiter which is used to figure out when the command's output ends.

This is where my memory is a bit fuzzy. I do recall that using the `echo -n` fallback where it is not needed causes it to become visible. In your examples, I also see that the commands generated by the framework (like `cat /etc/*release*`) are also printed back in the terminal, which shouldn't be the case. This could be either linked to your specific terminal's settings, or it could be another bug in FFM...

I hope this helps!

**Comment by JusticeRage** [comment]
Not in the near future at least, maybe not ever. Since I now work on defense full-time, I don't have any occasion to play with the framework and use it in real-life. If that were to change, then I would surely start adding features again, but this is just not planned at the moment.
I'll still happily merge any contributions from the community and fix critical bugs though!
